language: node_js
node_js:
  - "node"

intall:
  - npm install -g nyc
  - npm install -g codecov
  - npm install -g mocha

script:
  - export TESTING="true"
  - npx nyc --reporter=lcov npm mtest && npx codecov

# this must be depricated because it can only properly review the code with the bot's token.
#### install:
#  - npm install -g codecov
#  - npm install -g istanbul
#script:
#  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#  - codecov